Remove Dockerfile. Copy Dockerfile.cvp to Dockerfile.quill. Switch from \'-\' to \'.\' separator. Remove JDK from Dockerfile.quill. Use FullStaq ruby 2.7.x.
Mckesson-cds/ci-docker-images pull request #41
Opened 2021-03-20 02:00 UTC by mileslane

### Changes

1. git rm Dockerfile
2. git cp Dockerfile.cvp Dockerfile.quill
3. git mv Dockerfile-cds-tools Dockerfile.cds-tools
4. git mv Dockerfile-chefdk Dockerfile.chefdk
5. ruby 2.7.x for quill
6. Remove the JDK from the quill image

2021-03-20 17:05 UTC, olbrich approved these changes
Looks good, add the comments and then you will need to let all the images build before github will let you merge it.

2021-03-20 17:05 UTC, olbrich commented on Dockerfile.cvp
> +  curl libcurl4-openssl-dev \
Why is this needed? Also, please keep each package on a single line in alphabetical order.

2021-03-20 17:05 UTC, olbrich commented on Dockerfile.cvp
> +  zlib1g-dev \
What is this for?
Maybe add a comment after the `\` indicating why it was needed.

2021-03-20 18:09 UTC, mileslane commented on Dockerfile.cvp
> +  curl libcurl4-openssl-dev \
Done and commented.

2021-03-20 18:09 UTC, mileslane commented on Dockerfile.cvp
> +  zlib1g-dev \
Commented.

2021-03-20 21:16 UTC, olbrich commented on Dockerfile.cds-tools
> +  zlib1g-dev `# Fixes 'zlib is missing; necessary for building libxml2'` \
Does this happen when installing a gem?

2021-03-20 21:17 UTC, olbrich commented on Dockerfile.chefdk
> +  libpq-dev `# Needed to provide libpq-fe.h header to build 'pg' gem native extensions` \
Does ChefDK even need the `pg` gem?

2021-03-21 03:09 UTC, mileslane commented on Dockerfile.cds-tools
> +  zlib1g-dev `# Fixes 'zlib is missing; necessary for building libxml2'` \
I believe it is nokogiri extensions

2021-03-21 03:12 UTC, mileslane commented on Dockerfile.chefdk
> +  libpq-dev `# Needed to provide libpq-fe.h header to build 'pg' gem native extensions` \
I doubt it, but if the application source is pulled in and there is a bundle install, it'll want to build the gem extensions, right?

2021-03-21 13:10 UTC, olbrich commented on Dockerfile.cds-tools
> +  zlib1g-dev `# Fixes 'zlib is missing; necessary for building libxml2'` \
If this is related to nokogiri then maybe this should be
```suggestion
  zlib1g-dev `# For nokogiri -- fixes 'zlib is missing; necessary for building libxml2'` \
```

2021-03-21 13:17 UTC, olbrich requested changes

2021-03-21 13:17 UTC, olbrich commented on Dockerfile.cds-tools
> +  imagemagick \
I think this relates to the 'rmagick' gem.

2021-03-21 13:17 UTC, olbrich commented on Dockerfile.cds-tools
> +  libmagickwand-dev \
These are also needed for `rmagick`

2021-03-21 13:17 UTC, olbrich commented on Dockerfile.cds-tools
> +  libpq-dev `# Needed to provide libpq-fe.h header to build 'pg' gem native extensions` \
```suggestion
  libpq-dev `# Needed for 'pg' gem` \
```

2021-03-21 13:17 UTC, olbrich commented on Dockerfile.chefdk
> +  libpq-dev `# Needed to provide libpq-fe.h header to build 'pg' gem native extensions` \
I think we can remove this one.

2021-03-21 13:17 UTC, olbrich commented on Dockerfile.cvp
> +  zlib1g-dev `# Fixes 'zlib is missing; necessary for building libxml2'` \
```suggestion
  zlib1g-dev `# needed for 'nokogiri' gem` \
```

2021-03-21 13:17 UTC, olbrich commented on Dockerfile.quill
> +  libpq-dev `# Needed to provide libpq-fe.h header to build 'pg' gem native extensions` \
```suggestion
  libpq-dev `# Needed for 'pg' gem` \
```

2021-03-21 13:17 UTC, olbrich commented on Dockerfile.quill
> +  zlib1g-dev `# Fixes 'zlib is missing; necessary for building libxml2'` \
```suggestion
  zlib1g-dev `# Needed for 'nokogiri' gem` \
```

2021-03-23 15:57 UTC, Josephrfarmer approved these changes
Approved based on Kevin's changes being addressed. 👍🏼

2021-03-23 15:58 UTC, hedwards98 approved these changes

2021-03-23 20:59 UTC, olbrich approved these changes

2021-03-23 21:04 UTC, merged